### ISSUE TITLE
Clicking link in Google spreadsheet stopped working; work-around: disable tab modifier

### ISSUE THREAD

**Issue by jbyers2** [furybee/chrome-tab-modifier#216] opened 2021-01-14 17:07 UTC
### Tab Modifier version 

0.22.0

### Browser

Chrome Version 87.0.4280.141 (Official Build) (64-bit)

### Expected behavior

Clicking hyperlink in Google Sheets opens in new tab; this has worked properly in the past. 

### Actual behavior

produces error message in same tab as opened Google Sheets:
"Your file couldn’t be accessed
It may have been moved, edited, or deleted.
ERR_FILE_NOT_FOUND"

### Steps to reproduce the behavior

1. open Google Sheets spreadsheet
2. click a hyperlink
3. see error message in same tab

**Comment by sylouuu** [comment] 2024-06-07 14:31
Hello @jbyers2,

I can't reproduce with the latest version 1.0.2.

Closing.

Bests

**Closed by sylouuu** 2024-06-07 14:31 UTC
Labels: type: bug
