### ISSUE TITLE
doesn't work

### ISSUE THREAD

**Issue by isw866** [furybee/chrome-tab-modifier#380] opened 2024-09-13 05:35 UTC
doesn't work on chrome v130.0.6715.0(canary)

**Comment by ciltocruz** [comment] 2024-09-13 22:45
Related? #378

**Comment by isw866** [comment] 2024-09-14 00:48
> Related? #378 相关？ #378

m not sure but these issuses seem similar

**Comment by sebastienfontaine** [comment] 2024-09-15 09:36
Duplicate of https://github.com/furybee/chrome-tab-modifier/issues/378

**Closed by sebastienfontaine** 2024-09-15 09:36 UTC
