### ISSUE TITLE
no way to remove the context menu item

### ISSUE THREAD

**Issue by WIZARDELF** [furybee/chrome-tab-modifier#101] opened 2017-09-16 16:13 UTC
as an open app, tab-modifier should provide users an option to remove its context menu item.

**Comment by sylouuu** [comment] 2017-10-20 10:28
Hello,

Thanks for the suggestion, no ETA for this.

Best

**Comment by Quenz** [comment] 2019-03-08 01:12
I second this. I'll never use the context menu item when clicking on a page, so it's just clutter.

**Comment by sylouuu** [comment] 2024-03-28 15:01
Duplicate of #249

**Closed by sylouuu** 2024-03-28 15:01 UTC
Labels: type: feature
