### ISSUE TITLE
Feature Request: Use Bookmark Names for tab names

### ISSUE THREAD

**Issue by drewmie** [furybee/chrome-tab-modifier#182] opened 2019-02-21 17:59 UTC
Feature Request: Use Bookmark names for tab names.  A tab rule would override this behavior.

Benefit #1: People already use Bookmarks extensively.  This would allow users to rename tabs by simply adding a Bookmark and naming it, without ever going into Tab Rules.

Benefit #2: This would automatically allow different tab names for different Google users, since every Google user signed into Chrome has their own Bookmarks.

Thanks.  I love Tab Modifier!

**Comment by sylouuu** [comment] 2024-03-28 13:35
Duplicate of #229

**Closed by sylouuu** 2024-03-28 13:35 UTC
