### ISSUE TITLE
Rules aren't Applied on ReOpen

### ISSUE THREAD

**Issue by fabianbanu** [furybee/chrome-tab-modifier#379] opened 2024-09-12 22:49 UTC
Rules are not applied after closing and reopening the tab. 

Each time I reopen the url, I must save the rule again to get the custom title and icon back.

This is on Google Chrome and Opera Browser.

**Comment by sebastienfontaine** [comment] 2024-09-15 09:44
Hello @fabianbanu, 

I am unable to reproduce your issue. Could you please use the template below to provide more details?

```
**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Extension version:** `X.Y.Z`

_Can be found here: chrome://extensions/?id=hcbgadmbdkiilgpifjgcakjehmafcjai_

**Additional context**
Add any other context about the problem here.
```

Best regards,

**Comment by fabianbanu** [comment] 2024-09-19 11:31
Hi @sebastienfontaine 

I've figured out how to reproduce this bug! 

I realize I often visit the same set of links for work from a  _folder of bookmarks_ in Chrome. 
When the page is first opened from specifically the bookmark, the rules for that URL do not apply _until_ I refresh the page. 

I think this is due to a discrepancy between saved bookmark and actual page URL, probably solved by using 'contains' instead of 'exact' for the rule. 

Perhaps this doesn't need addressing. 

Thanks for the great product.

**Comment by sebastienfontaine** [comment] 2024-10-05 21:08
Hi! This is probably resolved by using ‘contains’ instead of ‘exact’ for the rule. Thanks for sharing the link to the favicon resource and for your feedback on the extension! I appreciate it! 🥳

**Closed by sebastienfontaine** 2024-10-05 21:08 UTC
